# Write pipeline for checkout code(git already exists), maven , unit tests, docker build, docker push, deploy to k8s? docker hub creds in jenkind credentials and k8s config is with jenkins server?

pipeline {
    agent any

    environment {
        APP_NAME = 'webapp'
        DOCKER_IMAGE = 'dockerhub/webapp'
        DOCKER_TAG = '${BUILD_NUMBER}'
        KUBECONFIG = '/var/lib/jenkins/.kube/config'
    }

    tools {
        maven 'maven-3.9'
    }

    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }

        stage('maven-build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('unit-test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('docker-build') {
            steps {
                sh '''
                docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                '''
            }
        }

        stage('docker-push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId = 'docker-hub-creds', // configured in jenkins cred store
                    usernameVariable = 'DOCKER_USER',
                    passwprdVariable = 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                    docker logout
                    '''
                }
            }
        }
        
        stage('Deplpoy to k8s') {
            steps {
                sh '''
                kubectl set image deployment/${APP_NAME} ${APP_NAME}=${DOCKER_IMAGE}:${DOCKER_TAG} --record
                kubect rollout status deployment/${APP_NAME}
                '''

                // if kubecongig stored in jenkins credentials
                //withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                //    sh 'kubectl get nodes'
              //  }   
            }
        }

        stage('rollout status') {
            steps {
                sh '''
                kubectl rollout status deployment/${APP_NAME} --timeout=60s
                '''
            }
        }
    }

    post {
        failure {
            echo "Deployment failed - rolling back"
            sh '''
            kubectl rollout undo deployment/${APP_NAME}

            // rollback to specific version
            kubectl rollout history deployment ${APP_NAME}
            kubectl rollout undo deployment ${APP_NAME} --to-revision=2

            '''
        }
    }
}